import numpy
try:
    import pymesh
    HAS_PYMESH = True
except Exception:
    HAS_PYMESH = False
"""
read_ply.py: Save a ply file to disk using pymesh and load the attributes used by MaSIF. 
Pablo Gainza - LPDI STI EPFL 2019
Released under an Apache License 2.0
"""


def save_ply(
    filename,
    vertices,
    faces=[],
    normals=None,
    charges=None,
    vertex_cb=None,
    hbond=None,
    hphob=None,
    iface=None,
    normalize_charges=False,
):
    if HAS_PYMESH:
        mesh = pymesh.form_mesh(vertices, faces)
        if normals is not None:
            n1 = normals[:, 0]
            n2 = normals[:, 1]
            n3 = normals[:, 2]
            mesh.add_attribute("vertex_nx")
            mesh.set_attribute("vertex_nx", n1)
            mesh.add_attribute("vertex_ny")
            mesh.set_attribute("vertex_ny", n2)
            mesh.add_attribute("vertex_nz")
            mesh.set_attribute("vertex_nz", n3)
        if charges is not None:
            mesh.add_attribute("charge")
            if normalize_charges:
                charges = charges / 10
            mesh.set_attribute("charge", charges)
        if hbond is not None:
            mesh.add_attribute("hbond")
            mesh.set_attribute("hbond", hbond)
        if vertex_cb is not None:
            mesh.add_attribute("vertex_cb")
            mesh.set_attribute("vertex_cb", vertex_cb)
        if hphob is not None:
            mesh.add_attribute("vertex_hphob")
            mesh.set_attribute("vertex_hphob", hphob)
        if iface is not None:
            mesh.add_attribute("vertex_iface")
            mesh.set_attribute("vertex_iface", iface)
        pymesh.save_mesh(filename, mesh, *mesh.get_attribute_names(), use_float=True, ascii=True)
        return
    vertices = numpy.asarray(vertices)
    faces = numpy.asarray(faces)
    n = len(vertices)
    m = len(faces)
    if normals is None:
        normals = numpy.zeros((n, 3))
    if charges is None:
        charges = numpy.zeros(n)
    if normalize_charges:
        charges = charges / 10
    if hbond is None:
        hbond = numpy.zeros(n)
    if hphob is None:
        hphob = numpy.zeros(n)
    if iface is None:
        iface = numpy.zeros(n)
    with open(filename, "w") as f:
        f.write("ply\n")
        f.write("format ascii 1.0\n")
        f.write("comment Generated by PyMesh\n")
        f.write("element vertex {}\n".format(n))
        f.write("property float x\n")
        f.write("property float y\n")
        f.write("property float z\n")
        f.write("property float nx\n")
        f.write("property float ny\n")
        f.write("property float nz\n")
        f.write("property float charge\n")
        f.write("property float hbond\n")
        f.write("property float vertex_hphob\n")
        f.write("property float vertex_iface\n")
        f.write("element face {}\n".format(m))
        f.write("property list uchar int vertex_indices\n")
        f.write("end_header\n")
        for i in range(n):
            v = vertices[i]
            nn = normals[i]
            f.write("{:.6f} {:.6f} {:.6f} {:.6f} {:.6f} {:.6f} {:.6f} {:.6f} {:.6f} {:.6f}\n".format(v[0], v[1], v[2], nn[0], nn[1], nn[2], float(charges[i]), float(hbond[i]), float(hphob[i]), float(iface[i])))
        for tri in faces:
            f.write("3 {} {} {}\n".format(int(tri[0]), int(tri[1]), int(tri[2])))
