import argparse
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ply", required=True)
    args = parser.parse_args()
    path = Path(args.ply)
    txt = path.read_text(errors="ignore").splitlines()
    nv = 0
    nf = 0
    st = 0
    props = []
    for i, l in enumerate(txt):
        if l.startswith("element vertex"):
            nv = int(l.split()[2])
        if l.startswith("property float"):
            props.append(l.split()[-1])
        if l.startswith("element face"):
            nf = int(l.split()[2])
        if l.strip() == "end_header":
            st = i + 1
            break
    verts = [ln.split() for ln in txt[st : st + nv]]
    faces = txt[st + nv : st + nv + nf]
    p2i = {p: i for i, p in enumerate(props)}
    new_rows = []
    for sp in verts:
        x = sp[p2i["x"]] if "x" in p2i else "0.0"
        y = sp[p2i["y"]] if "y" in p2i else "0.0"
        z = sp[p2i["z"]] if "z" in p2i else "0.0"
        nx = sp[p2i["nx"]] if "nx" in p2i else (sp[p2i["vertex_nx"]] if "vertex_nx" in p2i else "0.0")
        ny = sp[p2i["ny"]] if "ny" in p2i else (sp[p2i["vertex_ny"]] if "vertex_ny" in p2i else "0.0")
        nz = sp[p2i["nz"]] if "nz" in p2i else (sp[p2i["vertex_nz"]] if "vertex_nz" in p2i else "0.0")
        iface = sp[p2i["iface"]] if "iface" in p2i else "0.0"
        viface = sp[p2i["vertex_iface"]] if "vertex_iface" in p2i else "0.0"
        charge = sp[p2i["charge"]] if "charge" in p2i else (sp[p2i["vertex_charge"]] if "vertex_charge" in p2i else "0.0")
        hbond = sp[p2i["hbond"]] if "hbond" in p2i else (sp[p2i["vertex_hbond"]] if "vertex_hbond" in p2i else "0.0")
        hphob = sp[p2i["hphob"]] if "hphob" in p2i else (sp[p2i["vertex_hphob"]] if "vertex_hphob" in p2i else "0.0")
        new_rows.append([x, y, z, iface, charge, hbond, hphob, nx, ny, nz, viface])
    out = [
        "ply",
        "format ascii 1.0",
        "comment Generated by PyMesh",
        f"element vertex {len(new_rows)}",
        "property float x",
        "property float y",
        "property float z",
        "property float iface",
        "property float charge",
        "property float hbond",
        "property float hphob",
        "property float nx",
        "property float ny",
        "property float nz",
        "property float vertex_iface",
        f"element face {len(faces)}",
        "property list uchar int vertex_indices",
        "end_header",
    ]
    out.extend([" ".join(v) for v in new_rows])
    out.extend(faces)
    bak = path.with_suffix(path.suffix + ".bak_before_reorder")
    if not bak.exists():
        bak.write_text("\n".join(txt) + "\n")
    path.write_text("\n".join(out) + "\n")
    print("rewrote", path)


if __name__ == "__main__":
    main()
